version: '3.8'

services:
  api:
    build: .
    container_name: skillflow_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://skillflow_user:password@db:5432/skillflow_db"
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:16
    container_name: skillflow_db
    restart: always
    environment:
      POSTGRES_DB: skillflow_db
      POSTGRES_USER: skillflow_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
